sudo: required
services:
- docker

before_install:
- docker build -t olegpochanskiy/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run olegpochanskiy/react-test npm test -- --coverage

after_success:
- docker build -t olegpochanskiy/multi-client ./client
- docker build -t olegpochanskiy/multi-nginx ./nginx
- docker build -t olegpochanskiy/multi-server ./server
- docker build -t olegpochanskiy/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push olegpochanskiy/multi-client
- docker push olegpochanskiy/multi-nginx
- docker push olegpochanskiy/multi-server
- docker push olegpochanskiy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-852560830756
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY